print('Fritz berkata, "Pearl,maukah engkau menjadi kekasihku?"')
print('Pearl menjawab, "Untuk apa aku jadi kekasihmu?"')
print('"Aku menyukaimu sejak lama, Pearl."jawab Fritz')
print('"Namun, untuk apa aku harus menerimamu? bukankah masih banyak perempuan lain di dunia ini?" begitu jawab Pearl')
print('Fritz menjawab, "Kau adalah wanita yang sempurna untukku, pearl" ')
print('"Engkau memanglah lelaki yang baik, Fritz. Namun maaf, Aku sedang menyukai orang lain." Jawab pearl tidak enak')
print('"oh baiklah tidak apa-apa pearl, semoga lelaki itu menjadi pilihan yang baik untukmu." Kata Fritz sambil menahan rasa perih di hati')
print('"Terima kasih Fritz." Jawab pearl')
print('Fritz pun pulang setelah mengalami patah hati untuk kesekian kalinya')
print('The End')
